# Site settings
email: gajeshbht@gmail.com
baseurl: "/Blog"
paginate: 6
paginate_path: "/Blog/page-:num"
google_analytics: 

# SEO settings
title: Biting Bits
description: A Blog on Software and Technolgy.
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Gajesh Bhat
profile_img: 
profile: 
social:
github: https://github.com/gajeshbhat

# Build settings
exclude: ["Gemfile", "Gemfile.lock", "LICENSE.txt"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
